name: Ecosystem API CD

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: docker pull niltongabriel/ecosystem-api:latest

      - name: Romeve old DOcker Container
        run: docker stop ecosystem-api || true

      - name: Run Docker container
        run: docker run --name ecosystem-api -d -p 8080:8080 niltongabriel/ecosystem-api:latest
