name: Ecosystem API CI

on: 
  pull_request: 
    branches: 
      - main
      - dev
    types: [ opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package -DskipTests

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Test with Maven
        run: mvn test

  docker: 
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-actions@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-actions@v3

      - name: Login to Docker HUB
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-actions@v5
        with:
          push: true
          tags: niltongabriel/ecosystem-api:latest

